#!/usr/bin/env python3
"""
Copyright (C) 2025 Henryk Szal (hesolium@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import sys
import time
import traceback

# hidden imports for other modules
import shlex
import aiohttp
import edge_tts

def exitMsg(*lst, returnValue=1):
    if lst:
        print(*lst)
    sys.exit(returnValue)

if sys.version_info.major >= 3 and sys.version_info.minor >= 13:
    exitMsg('The program requires Python version 3.12 or lower.')

import os
frozen = getattr(sys, '_MEIPASS', None)
if frozen is not None:
    fdir = frozen + os.pathsep
    if fdir not in os.environ["PATH"]:
        os.environ["PATH"] = fdir + os.environ["PATH"]
    # print(os.environ["PATH"])
    fdir = os.getcwd()
    if fdir not in os.environ["PATH"]:
        sys.path.insert(-1, fdir)
    # print(sys.path)

import iso639
import argparse
import shutil
import subprocess
import mimetypes
from collections import namedtuple
from tempfile import TemporaryDirectory
from typing import Optional
from alive_progress import alive_bar
from pathlib import Path
import importlib.util
from pysrt import SubRipFile, SubRipItem
from pydub import AudioSegment as AdSeg, AudioSegment
from pydub.silence import split_on_silence, detect_leading_silence
import pysrt
from gtts import gTTS
from configparser import ConfigParser
import runpy

__version__ = "0.5.0"
MovieTrack = namedtuple('MovieTrack', 'idx, codec_type, codec_name, language, duration')
tmp_mp3: str = "-tmpSpeech.mp3"
tmp_wav: str = "-tmpSpeech.wav"
tmp_wav2: str = "-tmpSpeech2.wav"
tmp_merge: str = "-tmpAudioMerge.aac"
tmp_2audios: str = "-tmp_merged2audios."
dir_handle:str = ""
nativeSpeech: Optional[AudioSegment] = None
lector: Optional[AudioSegment] = None
defFrameRate = 24000
args = None

formatIdx = '03d'
subs:Optional[SubRipFile] = None
subsCount = 0
barStyle = {
    "bar":'classic',
    "spinner": "classic"
}
usage = \
"Version " + __version__ + " Copyright (c) 2025\n"\
"Generate a voice-over audio based on a specified subtitle file\n\n"\
"Positional argument (.srt file name) is not obligatory\n"\
"Subtitles and/or original audio can be extracted directly from video file (-n option)\n"\

def isEmpty(s, attr: str = None) -> bool:
    if s and attr:
        s = getattr(s, attr, None)
    if not s:
        return True
    if type(s) is str:
        return s.isspace()
    elif type(s) in (int, float):
        return False
    return len(s) == 0

# Accelerate speech generated by Google (gTTS)
def changeSpeed(inFile: str, outFile: str, s_ratio: float, g_ratio: float):
    if s_ratio == 0:
        s_ratio = 1.0
    arguments = ["audio-stretch", "-q", "-y", "-r" + str(s_ratio)]
    if g_ratio != 1.0 and g_ratio != 0:
        arguments.append("-g" + str(g_ratio))
    arguments.append(inFile)
    arguments.append(outFile)
    rv = subprocess.run(arguments)
    return rv.returncode

def verbose(*fArgs):
    if args.verbose > 0:
        print(*fArgs)

def quiet(*fArgs, **kwargs):
    if args.verbose > 0 or not args.quiet:
        print(*fArgs, **kwargs)

def keepFragment(idx, merged):
    rv = None
    if args.fragments is not None:
        idx1 = idx + 1
        if len(args.fragments) == 0 or idx1 in args.fragments:
            fn = getFragmentPrefix(idx, merged)
            # save generated fragment voice for subtitle
            if os.path.isfile(tmp_mp3):
                rv = fn + ".mp3"
                if os.path.isfile(rv):
                    os.remove(rv)
                os.rename(tmp_mp3, rv)
    return rv

def generate_gtts(text, outFile):
    if os.path.isfile(outFile):
        os.remove(outFile)
    maxTry = 3
    while maxTry > 0:
        try:
            sFrag = gTTS(text=text, lang=args.language, slow=False)
            sFrag.save(tmp_mp3)
            break
        except OSError:
            if not args.quiet:
                print("Network error! Sleep for 5 seconds and try again...")
            time.sleep(5)
            maxTry -= 1
            if maxTry == 0:
                print("Generating voice for '" + text + "' failed")
                sys.exit(1)

def createVoice(txt: str):
    if args.voiceGenerator is None:
        generate_gtts(txt, tmp_mp3)
    else:
        args.voiceGenerator.generateVoice(txt, tmp_mp3)
    sFrag = AdSeg.from_mp3(tmp_mp3)
    dur = len(sFrag)
    sFrag = trimSilence(sFrag)
    if len(sFrag) != dur:
        sFrag.export(tmp_mp3)
    return sFrag

def trimSilence(voice: AudioSegment):
    duration = len(voice)
    start = detect_leading_silence(voice)
    end = detect_leading_silence(voice.reverse())
    if start > 0 or end < duration:
        voice = voice[start:duration - end]
    return voice

# Generate speech from text.
def genFragment(txt: str, idx: int, merged: int):
    tmp3File = sFrag = None
    if os.path.isfile(tmp_mp3):
        os.remove(tmp_mp3)
    if args.usePreloaded:
        fn = getFragmentPrefix(idx, merged) + ".mp3"
        if os.path.isfile(fn):
            tmp3File = fn
    if tmp3File is None:
        # mp3 file not preloaded. Get speech from external source
        sFrag = createVoice(txt)
        fn = keepFragment(idx, merged)
        tmp3File = fn if fn is not None else tmp_mp3
    if not args.preloadOnly:
        if sFrag is None:
            sFrag = AdSeg.from_mp3(tmp3File)
        sFrag.export(tmp_wav, format="wav")
        if (args.accelerate != 0.0 and args.accelerate != 1.0) or (args.gapAccelerate != 0.0 and args.gapAccelerate != 1.0):
            changeSpeed(tmp_wav, tmp_wav2, args.accelerate, args.gapAccelerate)
            sFrag = AdSeg.from_wav(tmp_wav2)
    return sFrag

def getFragmentPrefix(idx: int, merged: int):
    idx1 = idx + 1
    fn = format(idx1, formatIdx)
    if merged > 0:
        fn += "-" + str(idx1 + merged)
    if args.subtitleBasename is not None:
        fn = args.subtitleBasename + "-" + fn
    fl = os.path.join(args.fragmentsDir, fn)
    return fl

def generateFragment(idx: int):
    global args, subs
    sb = getSubtitle(idx)
    txt = sb.text
    verbose("Subtitle", idx + 1, ':', txt)
    verbose("Time range: [", sb.start, ",", sb.end, "]  Duration:", sb.duration.ordinal, "ms")
    skipSub = 0
    sFrag = genFragment(txt, idx, skipSub)
    if args.preloadOnly:
        return None, 0, 0
    sb2 = getSubtitle(idx + 1)
    orgLen = len(sFrag)
    sgap = (sb2.start - sb.start).ordinal if sb2 else orgLen
    verbose("Speech segment len:", orgLen, "ms")
    if 0 < sgap < orgLen:
        # try to concatenate with next subtitle
        if sb2:
            txt2 = txt + ' ' + sb2.text
            skipSub = 1
            sFrag = genFragment(txt2, idx, skipSub)
            orgLen = len(sFrag)
            sb3 = getSubtitle(idx + 2)
            sgap = (sb3.start - sb.start).ordinal if sb3 else orgLen
            verbose("Gap too small. Concatenated sub:", txt2)
            verbose("Concatenated gap len:", sgap, "ms")
        if 0 < sgap < orgLen and (0 < args.minAccelerate < 1.0 or 0 < args.minGapAccelerate < 1.0):
            # concatenation failed. Speed up speech
            verbose("Concatenated speech too long (", orgLen, "ms). Speed up.")
            if args.accelerate != 0.0 and args.accelerate != 1.0:
                orgLen /= args.accelerate
            nRatio = max(round(sgap / orgLen, 2), args.minAccelerate)
            proc = (nRatio - args.minAccelerate) / (1.0 - args.minAccelerate)
            gRatio = args.minGapAccelerate + (1.0 - args.minGapAccelerate) * proc
            gRatio = max(round(gRatio, 2), args.minGapAccelerate)
            verbose("New accelerate ratio:", nRatio, "gap ratio:", gRatio)
            changeSpeed(tmp_wav, tmp_wav2, nRatio, gRatio)
            sFrag = AdSeg.from_wav(tmp_wav2)
        verbose("New speech segment len:", len(sFrag), "ms")
    return sFrag, sgap, skipSub

def setFromConfig(langInfo):
    sat = [option for option in langInfo]
    for key in sat:
        latr = langInfo[key]
        if key == 'gapaccelerate':
            key = 'gapAccelerate'
        atr = getattr(args, key, None)
        if atr is None and latr is not None:
            setattr(args, key, latr)

def computeDB(frag):
    if args.silence is None:
        return round(frag.dBFS, 1)
    chunks = split_on_silence(frag, min_silence_len=args.silenceLength, silence_thresh=args.silenceThreshold, keep_silence=False,
                    seek_step=args.silenceStep)
    if len(chunks) == 0 or len(chunks[0]) == len(frag):
        return None
    lFragment = AdSeg.empty()
    for c in chunks:
        lFragment += c
    return round(lFragment.dBFS, 1)

def decodeAccelerate(val:str):
    ma = ra = 0
    if not isEmpty(val):
        t = val.split(':')
        ma = float(t[0])
        if len(t) > 1 and not isEmpty(t[1]):
            ra = float(t[1])
            args.stretch = True
    return ma, ra

def printNativeTracks():
    print("Native media type:", args.nativeMediaType)
    if len(args.nativeStreams) > 1:
        print("Streams in media file:")
        for t in range(len(args.nativeStreams)):
            s: MovieTrack = args.nativeStreams[t]
            lg = str(s.language.part1) if s.language is not None else 'None'
            print('Track:', s.idx, 'type:', s.codec_type, 'lang:', lg)

def badStreamsInfo(msg):
    if msg:
        print(msg)
    if len(args.nativeStreams) > 1:
        printNativeTracks()
        print("You can use option -t to specify tracks for processing")
    sys.exit(1)

def importExternalModule(mName):
    p = Path(mName)
    if p.suffix == '.py':
        mName = p.stem
    mod = importlib.import_module(mName)
    mod.args = args
    return mod

def showOptions():
    print("Fundamental options for voice generation:")
    if args.shift != 0:
        print("\tShift audio:", str(args.shift), "ms")
    if args.volume != 0.0:
        if args.relative:
            print("\tAudio gain relative to original audio volume:", str(args.volume), 'dB')
        else:
            print("\tAudio gain:", str(args.volume), 'dB')
    print("\tMax speed up voice by", args.minAccelerate, "ratio")
    print("\tMax speed up pauses between words.", args.minGapAccelerate, "ratio")
    if args.silenceLength != 0:
        print("\tOption for remove long silence between words:")
        print("\t\tMinimal length:", str(args.silenceLength), "ms")
        print("\t\tThreshold:", str(args.silenceThreshold), "dB")
        print("\t\tStep:", str(args.silenceStep))

def processArguments():
    global subsCount, subs, dir_handle, args, tmp_mp3, tmp_wav, tmp_wav2, tmp_merge, tmp_2audios, nativeSpeech
    args.verboseFile = None
    if args.verbose is not None:
        if not str(args.verbose).isdigit():
            args.verboseFile = open(args.verbose, "w", buffering=1)
            args.verbose = 1
        else:
            args.verbose = int(args.verbose)
    if args.config is None:
        cName = args.config = "srt2voice.ini"
        if not os.path.isfile(args.config) and frozen is not None:
            args.config = os.path.join(frozen, args.config)
            cName = "internal srt2voice.ini"
        if not os.path.isfile(args.config):
            args.config = None
    else:
        cName = args.config
    if args.config is not None:
        if not os.path.isfile(args.config):
            exitMsg("Specified INI file '" + args.config + "' was not found.")
        config = ConfigParser()
        config.read(args.config)
        sectionId = args.language
        if not isEmpty(args.voice):
            sectionId += ":" + args.voice
        langInfo = config[sectionId]
        if langInfo is not None:
            quiet("Process args from " + cName + " ["+ sectionId + "] section.")
            setFromConfig(langInfo)
        else:
            exitMsg("No section [" + sectionId + "] in " + cName + " file")
    else:
        print("No INI file was specified and no standard one (srt2voice.ini) was found.")
    args.fragments = args.fragmentsDir = None
    if args.keepFragments is not None:
        args.fragments = {}
        idx = args.keepFragments.rfind(':')
        if idx >= 0:
            if idx > 0:
                args.fragmentsDir = args.keepFragments[:idx]
            flist = args.keepFragments[idx + 1:]
            if len(flist) > 0:
                flist = flist.split(',')
                args.fragments = {int(x) for x in flist}
        else:
            args.fragmentsDir = args.keepFragments
    if args.fragmentsDir is None:
        dir_handle = TemporaryDirectory()
        args.tempDir = dir_handle.name
        if args.fragments is not None:
            args.fragmentsDir = ""
    else:
        if not os.path.isdir(args.fragmentsDir):
            exitMsg("Specified directory '" + args.fragmentsDir + "' was not found.")
        args.tempDir = args.fragmentsDir
    if args.nativeMedia is not None:
        getNativeStreams()
    args.srtTrackIdx = args.audioTrackIdx = None
    if args.tracks is not None:
        tok = args.tracks.split(':') if ':' in args.tracks else [args.tracks]
        for t in tok:
            if t.startswith('s'):
                args.srtTrackIdx = int(t[1:])
                if args.srtTrackIdx >= len(args.nativeStreams) or args.nativeStreams[args.srtTrackIdx].codec_type != 's':
                    badStreamsInfo("Incorrect subtitle track '" + t + "' specified")
            elif t.startswith('a'):
                args.audioTrackIdx = int(t[1:])
                if args.audioTrackIdx >= len(args.nativeStreams) or args.nativeStreams[args.audioTrackIdx].codec_type != 'a':
                    badStreamsInfo("Incorrect audio track '" + t + "' specified")
    args.subtitleBasename = Path(args.srtFile).stem if args.srtFile else None
    args.outDir = None
    if args.outFile is not None and os.path.isdir(args.outFile):
        args.outDir = args.outFile
        args.outFile = None
    if args.outFile is None:
        sf = ''
        if args.srtFile is not None:
            args.outFile = Path(args.srtFile).stem
        elif args.nativeMedia is not None:
            args.outFile = Path(args.nativeMedia).stem
    else:
        sf = Path(args.outFile).suffix
    if args.outFile is None:
        exitMsg("Unable to determine output file name. Specify -o option")
    tmp_mp3 = os.path.join(args.tempDir, args.outFile + tmp_mp3)
    tmp_wav = os.path.join(args.tempDir, args.outFile + tmp_wav)
    tmp_wav2 = os.path.join(args.tempDir, args.outFile + tmp_wav2)
    tmp_merge = os.path.join(args.tempDir, args.outFile + tmp_merge)
    tmp_2audios = os.path.join(args.tempDir, args.outFile + tmp_2audios)
    outExt = '.aac'
    if args.merge is not None:
        if 'v' in args.merge:
            outExt = Path(args.nativeMedia).suffix
        else:
            # args.merge == 'a':
            if args.nativeMediaType == 'v':
                if args.audioTrackIdx is None:
                    stream = getStream("a")
                else:
                    stream = args.nativeStreams[args.audioTrackIdx]
                outExt = '.' + stream.codec_name
            else:
                outExt = Path(args.nativeMedia).suffix
    if isEmpty(sf):
        if outExt == '.eac3':
            outExt = '.ac3'
        args.outFile += outExt
        args.outFileDeduced = True
    else:
        args.outFileDeduced = False
        if 'v' not in args.merge:
            # output file must be audio type
            mimetypes.init()
            ft = mimetypes.guess_type(args.outFile)
            if ft is not None:
                ft = ft[0].split('/')
                if ft[0] != 'audio':
                    exitMsg("Output file extension mismatch. Should be any type 'audio' supported by ffmpeg")
        elif sf != outExt:
            exitMsg("Video output file must have the same file extension as merged original media file")
    # Check if output file exists
    if args.outDir is not None:
        args.outFile = os.path.join(args.outDir, args.outFile)
    if os.path.isfile(args.outFile) and os.path.getsize(args.outFile) > 0:
        exitMsg("Output file '" + args.outFile + "' already exists")
    if args.nativeMedia:
        if args.srtFile is None:
            # SRT from movie file?
            if args.srtTrackIdx is not None:
                track = args.nativeStreams[args.srtTrackIdx]
                if track.codec_type != 's':
                    badStreamsInfo('Specified subtitle track ' + str(args.srtTrackIdx) + " is not proper type (subtitle)")
            else:
                track = getStream("s", args.isoLang)
            if track is not None:
                # extract SRT from media file
                extractTrack(args.nativeMedia, track)
                args.subtitleBasename = Path(args.nativeMedia).stem
                if args.merge:
                    # Merge subtitle unnecessary
                    args.merge = args.merge.replace("s", "")
    if not isEmpty(args.formatter):
        glob = {'args': args}
        if args.formatter.endswith('.py'):
            args.formatter = args.formatter[:-3]
        args.clearSrt = args.srtFile
        runpy.run_module(args.formatter, init_globals=glob, run_name= "__main__")
        # args.formatter = importExternalModule(args.formatter)
        # args.clearSrt = args.formatter.clean()
        if args.clearSrt != args.srtFile:
            quiet("Cleaned SRT file saved in:", args.clearSrt)
            if args.srtFile is None:
                args.srtFile = args.clearSrt
        else:
            args.clearSrt = args.srtFile
    else:
        args.clearSrt = args.srtFile
    # Try import options from INI file
    if args.merge and args.nativeMedia is None:
        exitMsg("Merge [-m] option specified but no native media file specified [-n].")
    # Preprocess options
    args.stretch = False
    args.minAccelerate, args.accelerate = decodeAccelerate(str(args.accelerate))
    args.minGapAccelerate, args.gapAccelerate = decodeAccelerate(str(args.gapAccelerate))
    if args.volume is not None:
        args.relative = args.volume[0] == 'r'
        if args.relative:
            if args.nativeMedia is None:
                exitMsg("Sound amplification relative to audio track volume is specified but no native media file option [-n] in args")
            args.volume = args.volume[1:]
        args.volume = float(args.volume)
    else:
        args.volume = 0
    args.shift = 0 if args.shift is None else int(args.shift)
    if isEmpty(args.silence):
        args.silence = None
    if args.silence is not None:
        sop = args.silence.split(':')
        args.silenceStep = int(sop[2]) if len(sop) > 2 else 1
        args.silenceThreshold = int(sop[1]) if len(sop) > 1 else -40
        args.silenceLength = int(sop[0]) if len(sop) > 0 else 500
    if args.clearSrt is not None:
        subs = pysrt.open(args.clearSrt)
        subsCount = len(subs)
    else:
        badStreamsInfo("No SRT source. SRT file name not given and no '" + args.language + "' subtitle in media file")
    if (args.relative or args.merge or args.keepFragments) and args.nativeMedia is not None and not args.preloadOnly:
        if args.audioTrackIdx is None:
            stream = getStream("a")
        else:
            stream = args.nativeStreams[args.audioTrackIdx]
        if stream.idx > 0:
            extractTrack(args.nativeMedia, stream)
            args.audioTrackIdx = stream.idx
        elif stream.idx == 0:
            if args.nativeMediaType != 'a':
                extractTrack(args.nativeMedia, stream)
            else:
                args.audioTrack = args.nativeMedia
        quiet("Load native audio file ... ", end='')
        nativeSpeech = AdSeg.from_file(args.audioTrack)
        quiet("loaded.")
    if not isEmpty(args.voiceGenerator):
        args.voiceGenerator = importExternalModule(args.voiceGenerator)
    if not args.preloadOnly and not args.quiet:
        showOptions()

def cmdOutput(cmdArgs:list, progressTime=0, barTitle=None):
    verbose("Run command:", cmdArgs)
    p = subprocess.Popen(cmdArgs, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
            bufsize=1, universal_newlines=True)
    stderrLines = []
    if progressTime > 0 and not args.quiet:
        mkv = (cmdArgs[0] == "mkvmerge")
        p_err = p.stderr
        p_out = p.stdout
        barInp = p_out if mkv else p_err
        with alive_bar(progressTime, title=barTitle, length=50, manual=True, **barStyle) as cbar:
            while True:
                line = barInp.readline()
                if not line:
                    break
                tm = None
                if mkv:
                    k = line.lower().find("progress")
                    if k >= 0:
                        proc = line[k + 9:]
                        proc = proc.strip().replace('%', '')
                        tm = int(proc) / 100
                elif 'size=' in line:
                    k = line.find(' time=')
                    if k > 0:
                        proc = line[k + 6:]
                        proc = proc.split()
                        if ':' in proc[0]:
                            tm = time2seconds(proc[0]) / progressTime
                if args.verboseFile is not None:
                    line = line.rstrip()
                    print(line, file=args.verboseFile, flush=True)
                if tm is None:
                    stderrLines.append(line)
                else:
                    cbar(tm)
            cbar(1.0)
        p.wait()
        if p.returncode != 0:
            p_err = "".join(stderrLines)
    else:
        p_out, p_err = p.communicate()
    if p.returncode != 0:
        print("\n**** Program execution error:", p.returncode)
        if not args.verbose:
            print(cmdArgs)
        msg = "\nProgram output:\n{0}".format(p_err)
        print(msg)
        traceback.print_stack()
        sys.exit(1)
    return p_out

def extractTrack(movieName, trackDes: MovieTrack):
    basename = Path(movieName).stem
    rest = " from media file. Track: " + str(trackDes.idx) + " Duration: " + str(int(trackDes.duration / 60)) + ":" + str(trackDes.duration % 60) + " min. "
    extraArgs = []
    if trackDes.codec_type == 's':
        args.srtFile = outFile = os.path.join(args.tempDir, basename + ".srt")
        tit ="Extract subtitle"
        extraArgs.append("-an")
    else:
        args.audioTrack = outFile = os.path.join(args.tempDir, basename + ".aac")
        tit ="Prepare reference audio"
        extraArgs += ["-ac", "1", "-sn"]
        # extraArgs.append("-sn")
    if args.usePreloaded and os.path.exists(outFile):
        quiet("File '" + outFile + "' already exists, skipping extraction")
        return "OK"
    car = ["ffmpeg", "-hide_banner", "-y", "-i", movieName, "-vn", "-map", "0:" + str(trackDes.idx)] + extraArgs + [outFile]
    tit += " to file '" + outFile + "'"
    tit += rest
    quiet(tit)
    out = cmdOutput(car, progressTime=trackDes.duration)
    if out is None:
        sys.exit(1)
    return out

def time2seconds(tm):
    t = tm.split(':')
    hours = int(t[0])
    minutes = int(t[1])
    sec = float(t[2])
    minutes += hours * 60
    sec += minutes * 60
    return int(sec)

def isNativeVideo():
    if args.nativeStreams:
        for t in args.nativeStreams:
            if t[1] == 'v':
                return True
    return False

def getDuration():
    # "ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 wszech.mp4"
    car = [
        "ffprobe", "-hide_banner", "-show_entries", "format=duration", "-show_entries",
        "stream=index,codec_type,codec_name,duration:stream_tags=language,duration", "-of", "compact=p=0", args.nativeMedia
    ]


def getNativeStreams():
    car = [
        "ffprobe", "-hide_banner", "-show_entries", "format=duration", "-show_entries",
        "stream=index,codec_type,codec_name:stream_tags=language,duration", "-of", "compact=p=0", args.nativeMedia
    ]
    out = cmdOutput(car)
    if not isEmpty(out):
        fileDuration = 0
        args.nativeMediaType = 'a'
        args.nativeStreams = []
        lst = out.split()
        for t in lst:
            t = t.lower()
            t = t.replace('tag:', '')
            w = t.split('|')
            sd = dict()
            sd["language"] = sd["duration"] = None
            add = True
            for desc in w:
                key, val = desc.split("=")
                if key == 'codec_type':
                    val = val[:1]
                    if val == 'v':
                        args.nativeMediaType = val
                elif key == 'duration':
                    if ':' in val:
                        val = time2seconds(val)
                    else:
                        fileDuration = int(float(val))
                        add = False
                elif key == 'index':
                    val = int(val)
                    key = "idx"
                elif key == 'language':
                    val = iso639.Language.match(val)
                sd[key] = val
            if add:
                args.nativeStreams.append(MovieTrack(**sd))
        if fileDuration != 0:
            for it in range(len(args.nativeStreams)):
                if args.nativeStreams[it].duration is None:
                    # noinspection PyProtectedMember
                    args.nativeStreams[it] = args.nativeStreams[it]._replace(duration=fileDuration)
        if args.verbose:
            printNativeTracks()

def getStream(sType, lang=None) -> Optional[MovieTrack]:
    if args.nativeStreams:
        for t in args.nativeStreams:
            if t.codec_type == sType:
                if lang and t.language != lang:
                    continue
                return t
    return None

def getSubtitle(idx) -> Optional[SubRipItem]:
    if idx >= len(subs):
        return None
    s = subs[idx]
    s.text = ' '.join(s.text.split())
    return s

def setMetaLang(aList: list, trackIdx: int):
    aList += ["-metadata:s:" + str(trackIdx), "language=" + args.language]

def extractSource():
    system = os.name
    files = [
        'README', 'requirements.txt', 'srt2voice.py', 'edge-gener.py', 'make-release', 'srt2voice.ini', 'audio-stretch',
        'cleanSubtitle.py', 'run-batch.py'
    ]
    print("Extract source files from package.")
    print(files)
    for file in files:
        src = os.path.join(frozen, file)
        dst = file
        if system == "nt":
            if file == "audio-stretch":
                src += '.exe'
                dst += '.exe'
            if file == "make-release":
                src += '.bat'
                dst += '.bat'
        shutil.copy(src, dst)
    sys.exit(0)

def normalizeFragment(voice: AudioSegment, sentence):
    if args.volume != 0.0:
        gain = args.volume
        if nativeSpeech and args.relative:
            fEnd = sentence.end.ordinal
            if skip > 0:
                fEnd = subs[i + 1].end.ordinal
            nFragment:AudioSegment = nativeSpeech[sentence.start.ordinal:fEnd]
            # meter = loudNormal.Meter(nFragment.frame_rate)  # create BS.1770 meter
            # fragDB = meter.integrated_loudness(nFragment.data)
            fragDB = round(nFragment.dBFS, 1)
            verbose("Original fragment dBFS:", fragDB)
            # compute gain relative, optionally remove silences from audio
            f = computeDB(nFragment)
            if f is not None:
                verbose("Original fragment dBFS after silence remove:", f)
                fragDB = f
            target = fragDB + gain
            gain = target - voice.dBFS
            voice = voice.apply_gain(gain)
            # voice = loudNormal.normalize.loudness(voice.data, loudness, gain)
        else:
            voice = voice.apply_gain(gain)
        verbose("Generated fragment dBFS after gain:", round(voice.dBFS, 1))
    return voice

def audioMixFilter():
    cFilter = "[0:a:0]" if args.audioTrackIdx is None else "[0:" + str(args.audioTrackIdx) + "]"
    cFilter += "[1:a]amix=inputs=2:normalize=0:duration="
    cFilter += "shortest" if args.maxSubtitles != 0 else "longest"
    return cFilter

def mix2audio():
    car = ["ffmpeg", "-hide_banner", "-y", "-i", args.nativeMedia, "-i", tmp_merge]
    cFilter = audioMixFilter()
    car += ["-filter_complex", cFilter]
    duration = int(len(nativeSpeech) / 1000)
    if args.nativeMediaType == 'v':
        car += ["-vn", "-sn", "-an"]
    if args.maxSubtitles != 0:
        global lector
        littleExpand = 5000  # in milliseconds
        if len(nativeSpeech) - len(lector) > littleExpand:
            lector = lector.append(AdSeg.silent(littleExpand, defFrameRate), crossfade=0)
        duration = int(len(lector) / 1000)
        car += ['-to', str(duration)]
        quiet("Audio truncated due to specified --maxSubtitles option!")
    audioCodec = args.nativeStreams[args.audioTrackIdx].codec_name
    if args.merge == 'a' and (audioCodec != 'eac3' or not args.outFileDeduced):
        toFile = args.outFile
    else:
        toFile = tmp_2audios + audioCodec
        car += ["-c:a", audioCodec]
    car.append(toFile)
    quiet("Merge voice-over '" + tmp_merge + "'" + " with original '" + args.nativeMedia + "' audio track")
    cmdOutput(car, progressTime=duration)
    if args.merge == 'a' and args.outFileDeduced and audioCodec == 'eac3':
        shutil.move(toFile, args.outFile)
        args.outFile = toFile
    return toFile

def mp4merge(mFile: str):
    sms = ""
    msg = " video"
    dur = ''
    if args.maxSubtitles != 0:
        dur = ':dur=' + str(int(len(lector) / 1000))
    car = ["mp4box", "-add", args.nativeMedia + dur, "-add", mFile + ':lang=' + args.language + dur]
    if 's' in args.merge:
        sms = " and subtitle"
        car += ["-add", args.srtFile + ':lang=' + args.language + dur]
    car += ["-new", args.outFile]
    end = os.linesep if args.verbose else ""
    quiet("Merge voice-over '" + mFile + "'" + sms + " with original '" + args.nativeMedia + "'" + msg + ' ... ', end=end)
    cmdOutput(car)
    quiet('Done')

def mkvMerge(mFile: str):
    car = ["mkvmerge", "-o", args.outFile, args.nativeMedia, "--language", '0:' + args.language, mFile]
    sms = ""
    if 's' in args.merge:
        sms = " and subtitle"
        car += ['0:' + args.language, args.srtFile]
    msg = " video"
    duration = 100
    car.append("--gui-mode")
    if args.maxSubtitles != 0:
        duration = int(len(lector) / 1000)
        car += ['--split', "parts:0s-" + str(duration) + "s"]
        duration = int((len(lector) / len(nativeSpeech)) * 100)
    quiet("Merge voice-over '" + mFile + "'" + sms + " with original '" + args.nativeMedia + "'" + msg)
    cmdOutput(car, progressTime=duration)

def mergeWithMedia():
    destFile = mix2audio()
    if destFile != args.outFile:
        # Add track to native video media
        if Path(args.outFile).suffix == '.mkv':
            mkvMerge(destFile)
            return
        elif Path(args.outFile).suffix == '.mp4':
            mp4merge(destFile)
            return
        print("WARNING! Running 'ffmpeg' to add audio file to video container is uncertain. Sometime produce corrupted audio track in movie.")
        print("Output files .mkv and .mp4 are supported natively (via mkvmerge and mp4box).")
        duration = int(len(nativeSpeech) / 1000)
        car = ["ffmpeg", "-hide_banner", "-y"]
        msg = ""
        end = os.linesep
        if args.maxSubtitles != 0:
            duration = int(len(lector) / 1000)
            car += ['-to', str(duration)]
            duration = 0
            msg = "..."
            if not args.verbose:
                end = ""
        car += ["-i", args.nativeMedia, "-i", destFile]
        sms = ""
        videoStreams = len(args.nativeStreams)
        if 's' in args.merge:
            car += ["-i", args.srtFile]
        car += ["-map", "0", "-map", "1"]
        setMetaLang(car, videoStreams)
        if 's' in args.merge:
            car += ["-map", "2"]
            setMetaLang(car, videoStreams + 1)
            sms = " and subtitle "
        # car += ["-c:v", "copy", "-c:s", "copy", "-c:a", "copy"]
        if args.maxSubtitles != 0:
            car += ['-shortest']
            quiet("Result truncated due to specified --maxSubtitles option!")
        car.append(args.outFile)
        quiet("Merge audio '" + destFile + "'" + sms + " with original '" + args.nativeMedia, msg, end=end)
        # args.verboseFile = open("merge.log", "w", buffering=1)
        # args.verbose = 1
        cmdOutput(car, progressTime=duration)
        if duration == 0 and not args.verbose:
            quiet(" done")

def runExternalScript():
    execFile = None
    if '-e' in sys.argv:
        execFile = sys.argv.index('-e')
    elif '--exec' in sys.argv:
        execFile = sys.argv.index('--exec')
    if execFile:
        sys.argv = sys.argv[execFile + 1:]
        if sys.argv[0].endswith('.py'):
            sys.argv[0] = sys.argv[0][:-3]
        print("Run external script:", sys.argv)
        print("Output from running script\n------------------------------------------------")
        runpy.run_module(sys.argv[0], run_name= "__main__")
        sys.exit(0)

if __name__ == '__main__':
    runExternalScript()
    parser = argparse.ArgumentParser(description=usage, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-l', '--language', required=(frozen is not None and '-e' not in sys.argv and '--extract' not in sys.argv),
            help="Subtitle language")
    parser.add_argument('-c', '--config',
            help="Config .ini file with language depended settings. Default 'srt2voice.ini'")
    parser.add_argument('-s', '--shift', help="Shift audio in milliseconds", type=int)
    parser.add_argument('-v', '--volume',
            help="Speech amplification in dB. If starts with 'r' then volume is relative to original audio volume level (-n option)")
    parser.add_argument('-a', '--accelerate', help="Minimal and regular speed up reading in form minValue:value")
    parser.add_argument('-g', '--gapAccelerate', help="Minimal and regular silence speed up in form minValue:value")
    parser.add_argument('-o', '--outFile',
            help="Output media file or directory. File name can be given without extension. It will be deduced from 'nativeMedia' type.")
    parser.add_argument('-n', '--nativeMedia', help="Original media file")
    parser.add_argument('-t', '--tracks',
            help="Specify tracks in movie to process. Tracks separated by ':'. Track format: <track type 's'/'a'><index> (e.g. -t s2:a3)")
    parser.add_argument('-m', '--merge', choices=['a', 'v', 'vs'],
            help="Merge generated audio with original audio[a] or video[v] or video+subtitle[vs] file (require -n option)")
    parser.add_argument('--formatter', default='cleanSubtitle.py',
            help="Module with defined function 'clean()'. See default formatter 'cleanSubtitle.py' for details")
    parser.add_argument('--voiceGenerator',
            help="Module with defined function 'generateVoice(text, outFile)'. Built-in generator use gTTS to generate voice")
    parser.add_argument('-q','--quiet', action='store_true',  default=False, help="Does not display any messages while processing.")
    parser.add_argument('-k', '--keepFragments',
            required=('-p' in sys.argv or '--preloadOnly' in sys.argv or '-u' in sys.argv or '--usePreloaded' in sys.argv),
            help="Save specified fragments in separate external files. Format: [directory][:list of fragment indexes separated by ',']")
    parser.add_argument('-p','--preloadOnly', action='store_true',
            help="Preload only .mp3 files for specified subtitles (option -k required)")
    parser.add_argument('-u','--usePreloaded', action='store_true',
            help="Use generated .mp3 files for subtitles stored in keepFragment directory (option -k required)")
    parser.add_argument('--verbose', help="Print info on every subtitle and generated voice", default=0)
    parser.add_argument('--silence', help="Removes the silence between subtitle words. Format: length:threshold:step")
    parser.add_argument('--voice', help="Voice for language if different ones are available.")
    parser.add_argument('--maxSubtitles', help="Max subtitles for process", type=int, default=0)
    parser.add_argument('--startSubtitle', help="Start index subtitle for process [index start from 1]", type=int, default=0)
    if frozen is not None:
        parser.add_argument('-e', '--exec', help="Executes a Python script using the frozen interpreter.")
        parser.add_argument('--extract', action='store_true', help="Extract source files from package")
    parser.add_argument("srtFile", nargs='?', help="Subtitle file name")
    args = parser.parse_args()
    if frozen is not None and args.extract:
        extractSource()
    try:
        args.isoLang = iso639.Language.match(args.language)
    except iso639.LanguageNotFoundError:
        exitMsg('Language', args.language, 'not found in ISO-639 standard table')
    processArguments()
    i = args.startSubtitle
    subsLen = subsCount if args.maxSubtitles == 0 else args.maxSubtitles
    stop = i + subsLen
    lector = AdSeg.empty()
    lgt = 50
    if subsCount < 100:
        formatIdx = '02d'
    elif subsCount >= 1000:
        formatIdx = '04d'
    title = "Preload speech fragments for subtitles" if args.preloadOnly else "Generate voice-over"
    with alive_bar(subsLen, title=title, length=lgt, disable=args.quiet, **barStyle) as bar:
        while i < stop:
            sent = getSubtitle(i)
            if not args.preloadOnly:
                verbose("--- Voice-over length", len(lector), "ms")
            speech, gap, skip = generateFragment(i)
            if not args.preloadOnly:
                verbose("Generated fragment dBFS:", round(speech.dBFS, 1))
                sft = 0
                if args.shift > 0:
                    sft = max(gap - len(speech), 0)
                    if sft > 0:
                        # Is free space to shift
                        sft = min(sft, args.shift)
                        if sft > 0:
                            verbose("Generated fragment shifted by", sft, "ms")
                    else:
                        sft = 0
                l_lector = len(lector)
                sTime = sent.start.ordinal - l_lector + sft
                # skip to start of subtitle
                if sTime > 0:
                    slc = AdSeg.silent(sTime, defFrameRate)
                    lector = lector.append(slc, crossfade=0)
                    l_lector = len(lector)
                normalizeFragment(speech, sent)
                if sft > 0:
                    verbose("Append to voice-over at", len(lector), "ms")
                lector = lector.append(speech, crossfade=0)
                verbose("")
            bar()
            i += 1
            if skip > 0:
                i += 1
                if i <= stop:
                    bar()
    if not args.preloadOnly:
        if not args.merge:
            fFormat = Path(args.outFile).suffix
            eFile = args.outFile
        else:
            fFormat = Path(tmp_merge).suffix
            eFile = tmp_merge
        fFormat = fFormat[1:]
        quiet("Save generated audio to file:", eFile)
        if fFormat == 'aac':
            fFormat = "adts"
        lector.export(eFile, format=fFormat)
        if args.merge:
            mergeWithMedia()
