[pl]
shift=700
volume=r11.0
# speed up generated speech
accelerate=0.6:0.8
# narrow pauses between words
gapAccelerate=0.5:0.6
# Remove pause between words options: min_length:dB_threshold:seek_step
silence=500:-40:10

[pl:pl-PL-MarekNeural]
shift=700
volume=r11.0
accelerate=0.7:
gapAccelerate=0.6:
silence=500:-40:10
pitch=-10Hz
